base: 'https://dev.xsite.ch/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-US
    direction: ltr
    flag: us
    languageId: '0'
rootPageId: 7
routes: {  }
