base: 'https://www.kayoscreed.ch/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=22'
languages:
  -
    title: EN
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_GB
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-GB
    direction: ltr
    flag: en-us-gb
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow:\r\nSitemap: https://www.kayoscreed.ch/sitemap.xml\r\n"
settings:
  redirects:
    autoUpdateSlugs: true
    autoCreateRedirects: false
    redirectTTL: 30
    httpStatusCode: 307
websiteTitle: ''
